spring.application.name=borrowit
spring.datasource.url=jdbc:mysql://localhost:3306/borrowitdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

frontend.url=http://localhost:4200


# Database Config

server.port=8088
server.servlet.context-path=/borrowit
logging.level.org.springframework.security=DEBUG

# Twilio Configuration
twilio.account.sid=AC8c699c74ae0adb7ef116ecd004311b86
twilio.auth.token=84f92e3fd0b99c4ff246f69870a7454b
twilio.phone.number=+18382137150


# Twilio2 Configuration



# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=66066421269-v32jkdsbjs13au3j5ao44qg403rrlpgq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/borrowit/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Database




# Email Config (Gmail)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=montaazzouz2@gmail.com
# spring.mail.password=hxtg apxu xhso kwxe
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# JWT Config



# App Specific

# Email Config (Gmail)


# Cloudinary
cloudinary.cloud-name=dtpbbdgut
cloudinary.api-key=651691567885534
cloudinary.api-secret=bdGTqlU0z_PFaSso70oAAmRBYOM

# Email Config (Gmail - utilise UNE SEULE adresse, ici celle de montassar)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=montaazzouz2@gmail.com
spring.mail.password=hxtg apxu xhso kwxe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# JWT Config
jwt.reset.secret=your-strong-secret-key-12345-change-me-for-production
jwt.reset.expiration=1800000

# App Specific
app.reset.path=/reset-password
stripe.api.secret.key=sk_test_51RBDOGQLnOgS0BJsoGXwC8mM6W66pFjDDXzl2RCfG8p1da9HdKnAZq1EmkvPrD0aHN1XwaE4KBjtOypotHQW3Vqz00iDzrJomu
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=montaazzouz2@gmail.com
#spring.mail.password=hxtg apxu xhso kwxe
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
