# Application name
spring.application.name=borrowit

# DataSource configuration for MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/borrowitdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration
server.port=8088
server.servlet.context-path=/borrowit

# Email configuration for Outlook SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vxinliu@gmail.com
spring.mail.password=none!!0000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

openrouter.api.key=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

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
